### ISSUE TITLE
Claves de autenticación

### ISSUE THREAD

**Issue by iblancasa** [ProyectCC/PeriodicoInteractivo#1]
En el fichero [script.py](https://github.com/ProyectCC/PeriodicoInteractivo/blob/master/script.py) habéis dejado las claves (tokens) de autenticación. 

Si algún bot las pilla, puede utilizarlas y dejaros sin el recurso que queráis usar. Cambiad los tokens y cambiar el código para que coja variables de entorno (por ejemplo).

**Comment by JCristobal** [comment]
Corregido, simplemente las hemos declarado dentro de Heroku:
![declaradas dentro de heroku](https://i.gyazo.com/669e562c8f177b0e17ba8fad0e585778.png)
